"""Alg week 8 tests. You do not edit this file."""

import sys

from check import Check
from exercises import (complement, has_vertex_cover, is_independent_set,
                       is_set_cover, is_vertex_cover, min_vertex_cover,
                       normalise, vertex_cover_to_set_cover, vertices_of,
                       verify_vertex_cover)

c = Check("Alg week 8 — NP-completeness")

SQUARE_PLUS = [("a", "b"), ("b", "c"), ("c", "d"), ("d", "a"), ("a", "c")]
PATH = [("a", "b"), ("b", "c"), ("c", "d")]
MATCHING = [("a", "b"), ("c", "d"), ("e", "f")]
K4 = [("a", "b"), ("a", "c"), ("a", "d"), ("b", "c"), ("b", "d"), ("c", "d")]
TRIANGLE = [("a", "b"), ("b", "c"), ("a", "c")]
GRAPHS = [SQUARE_PLUS, PATH, MATCHING, K4, TRIANGLE, []]

# -- plumbing ---------------------------------------------------------------
c.eq("normalise sorts and dedups",
     lambda: normalise([("b", "a"), ("a", "b"), ("b", "c")]),
     [("a", "b"), ("b", "c")])
c.eq("normalise([])", lambda: normalise([]), [])
c.eq("an undirected edge is one edge",
     lambda: len(normalise([("x", "y"), ("y", "x")])), 1)
c.eq("vertices_of", lambda: vertices_of(PATH), {"a", "b", "c", "d"})
c.eq("vertices_of([])", lambda: vertices_of([]), set())

# -- the definition, slide 15 ----------------------------------------------
c.true("one endpoint suffices", lambda: is_vertex_cover([("a", "b")], ["a"]))
c.true("the other endpoint also suffices", lambda: is_vertex_cover([("a", "b")], ["b"]))
c.true("both endpoints is still a cover",
       lambda: is_vertex_cover([("a", "b")], ["a", "b"]))
c.true("an unrelated vertex is not a cover",
       lambda: not is_vertex_cover([("a", "b")], ["c"]))
c.true("the empty cover covers the empty graph", lambda: is_vertex_cover([], []))
c.true("the empty cover does not cover an edge",
       lambda: not is_vertex_cover([("a", "b")], []))
c.true("every vertex set is a cover",
       lambda: all(is_vertex_cover(g, vertices_of(g)) for g in GRAPHS))
c.true("{a, c} covers the five-edge graph",
       lambda: is_vertex_cover(SQUARE_PLUS, ["a", "c"]))
c.true("{a, b} does not — edge c-d is uncovered",
       lambda: not is_vertex_cover(SQUARE_PLUS, ["a", "b"]))

# -- the verifier, slide 6 --------------------------------------------------
c.true("a valid certificate of the right size verifies",
       lambda: verify_vertex_cover(SQUARE_PLUS, 2, ["a", "c"]))
c.true("a valid cover that is too big is rejected",
       lambda: not verify_vertex_cover(SQUARE_PLUS, 1, ["a", "c"]))
c.true("an invalid cover of the right size is rejected",
       lambda: not verify_vertex_cover(SQUARE_PLUS, 2, ["a", "b"]))
c.true("a smaller valid cover still verifies against a larger k",
       lambda: verify_vertex_cover(SQUARE_PLUS, 4, ["a", "c"]))
c.true("duplicates in the certificate do not inflate its size",
       lambda: verify_vertex_cover(SQUARE_PLUS, 2, ["a", "c", "a", "c"]))
c.true("the empty certificate verifies for the empty graph",
       lambda: verify_vertex_cover([], 0, []))

# -- the optimisation version ----------------------------------------------
c.eq("minimum cover of the 5-edge graph has size 2",
     lambda: len(min_vertex_cover(SQUARE_PLUS)), 2)
c.eq("minimum cover of a 3-edge path has size 2",
     lambda: len(min_vertex_cover(PATH)), 2)
c.eq("a perfect matching needs one vertex per edge",
     lambda: len(min_vertex_cover(MATCHING)), 3)
c.eq("K4 needs 3", lambda: len(min_vertex_cover(K4)), 3)
c.eq("a triangle needs 2", lambda: len(min_vertex_cover(TRIANGLE)), 2)
c.eq("the empty graph needs none", lambda: min_vertex_cover([]), set())
c.true("what it returns really is a cover",
       lambda: all(is_vertex_cover(g, min_vertex_cover(g)) for g in GRAPHS))
c.true("no smaller cover exists",
       lambda: all(not any(is_vertex_cover(g, sub)
                           for sub in __import__("itertools").combinations(
                               sorted(vertices_of(g)), len(min_vertex_cover(g)) - 1))
                   for g in GRAPHS if min_vertex_cover(g)))

# -- the decision version, slide 4 -----------------------------------------
c.true("has_vertex_cover(G, 2) on the 5-edge graph",
       lambda: has_vertex_cover(SQUARE_PLUS, 2))
c.true("has_vertex_cover(G, 1) is false",
       lambda: not has_vertex_cover(SQUARE_PLUS, 1))
c.true("a bigger budget is still a yes", lambda: has_vertex_cover(SQUARE_PLUS, 3))
c.true("the empty graph has a cover of size 0", lambda: has_vertex_cover([], 0))
c.true("decision and optimisation agree",
       lambda: all(has_vertex_cover(g, k) == (len(min_vertex_cover(g)) <= k)
                   for g in GRAPHS for k in range(5)))

# -- independent sets -------------------------------------------------------
c.true("a single vertex is independent",
       lambda: is_independent_set([("a", "b")], ["a"]))
c.true("both endpoints of an edge are not",
       lambda: not is_independent_set([("a", "b")], ["a", "b"]))
c.true("the empty set is independent", lambda: is_independent_set(SQUARE_PLUS, []))
c.eq("complement", lambda: complement({"a", "b", "c"}, ["a"]), {"b", "c"})
c.eq("complement of everything is empty",
     lambda: complement({"a", "b"}, ["a", "b"]), set())

# The theorem in §6, checked on every graph and every subset.
def _duality(g):
    verts = sorted(vertices_of(g))
    for r in range(len(verts) + 1):
        for sub in __import__("itertools").combinations(verts, r):
            if is_vertex_cover(g, sub) != is_independent_set(g, complement(verts, sub)):
                return False
    return True

c.true("C is a vertex cover iff V\\C is independent (5-edge graph)",
       lambda: _duality(SQUARE_PLUS))
c.true("...and on K4", lambda: _duality(K4))
c.true("...and on a matching", lambda: _duality(MATCHING))

# -- the reduction, approx slide 14 ----------------------------------------
c.eq("one edge reduces to one ground element and two subsets",
     lambda: vertex_cover_to_set_cover([("a", "b")]),
     ({("a", "b")}, {"a": {("a", "b")}, "b": {("a", "b")}}))
c.eq("the ground set is the edges",
     lambda: vertex_cover_to_set_cover(SQUARE_PLUS)[0],
     lambda: set(normalise(SQUARE_PLUS)))
c.eq("there is one subset per vertex",
     lambda: sorted(vertex_cover_to_set_cover(SQUARE_PLUS)[1]), ["a", "b", "c", "d"])
c.eq("a vertex's subset is its incident edges",
     lambda: vertex_cover_to_set_cover(SQUARE_PLUS)[1]["b"],
     {("a", "b"), ("b", "c")})
c.eq("subset sizes are the vertex degrees",
     lambda: {v: len(s) for v, s in vertex_cover_to_set_cover(SQUARE_PLUS)[1].items()},
     {"a": 3, "b": 2, "c": 3, "d": 2})

c.true("is_set_cover on a trivial instance",
       lambda: is_set_cover({1, 2}, {"x": {1}, "y": {2}}, ["x", "y"]))
c.true("...and rejects an incomplete one",
       lambda: not is_set_cover({1, 2}, {"x": {1}, "y": {2}}, ["x"]))
c.true("the empty ground set is covered by nothing",
       lambda: is_set_cover(set(), {"x": {1}}, []))

# The reduction is only worth anything if it preserves solutions, both ways.
def _reduction_faithful(g):
    ground, subsets = vertex_cover_to_set_cover(g)
    verts = sorted(vertices_of(g))
    for r in range(len(verts) + 1):
        for sub in __import__("itertools").combinations(verts, r):
            if is_vertex_cover(g, sub) != is_set_cover(ground, subsets, sub):
                return False
    return True

c.true("a set of vertices covers the graph iff its subsets cover the edges",
       lambda: _reduction_faithful(SQUARE_PLUS))
c.true("...on K4", lambda: _reduction_faithful(K4))
c.true("...on a path", lambda: _reduction_faithful(PATH))
c.true("...on a matching", lambda: _reduction_faithful(MATCHING))

sys.exit(c.done())
