"""Alg week 9 tests. You do not edit this file."""

import math
import sys
from itertools import combinations

from check import Check
from exercises import (approximation_ratio, mst_edges, mst_weight,
                       optimal_tour_cost, satisfies_triangle_inequality,
                       tight_example, tour_cost, tsp_tour, vertex_cover_approx)

c = Check("Alg week 9 — approximation algorithms")

SQUARE_PLUS = [("a", "b"), ("b", "c"), ("c", "d"), ("d", "a"), ("a", "c")]
PATH = [("a", "b"), ("b", "c"), ("c", "d")]
K4 = [("a", "b"), ("a", "c"), ("a", "d"), ("b", "c"), ("b", "d"), ("c", "d")]
TRIANGLE = [("a", "b"), ("b", "c"), ("a", "c")]
GRAPHS = [SQUARE_PLUS, PATH, K4, TRIANGLE, [("x", "y")], []]


def _is_cover(edges, cover):
    return all(v in set(cover) or w in set(cover) for v, w in edges)


def _min_cover_size(edges):
    verts = sorted({v for e in edges for v in e})
    for size in range(len(verts) + 1):
        if any(_is_cover(edges, sub) for sub in combinations(verts, size)):
            return size
    return len(verts)


def _metric(points):
    return {u: {v: (0.0 if u == v else round(math.dist(points[u], points[v]), 6))
                for v in points} for u in points}


RECT = _metric({"a": (0, 0), "b": (0, 3), "c": (4, 3), "d": (4, 0)})
LINE = _metric({"a": (0, 0), "b": (1, 0), "c": (2, 0), "d": (5, 0)})
PENT = _metric({chr(97 + i): (math.cos(2 * math.pi * i / 5), math.sin(2 * math.pi * i / 5))
                for i in range(5)})
METRICS = [RECT, LINE, PENT]

# -- the algorithm, np slide 16 --------------------------------------------
c.eq("one edge gives both its endpoints",
     lambda: vertex_cover_approx([("a", "b")]), {"a", "b"})
c.eq("the empty graph gives the empty cover",
     lambda: vertex_cover_approx([]), set())
c.eq("the 5-edge graph gives all four vertices",
     lambda: vertex_cover_approx(SQUARE_PLUS), {"a", "b", "c", "d"})
c.true("what it returns is always a cover",
       lambda: all(_is_cover(g, vertex_cover_approx(g)) for g in GRAPHS))
c.true("it always takes an even number of vertices",
       lambda: all(len(vertex_cover_approx(g)) % 2 == 0 for g in GRAPHS))

# Slide 19's theorem, checked rather than believed.
c.true("np slide 19: |C| <= 2 * OPT on every test graph",
       lambda: all(len(vertex_cover_approx(g)) <= 2 * _min_cover_size(g)
                   for g in GRAPHS))
c.true("...and never smaller than OPT, since it is a cover",
       lambda: all(len(vertex_cover_approx(g)) >= _min_cover_size(g) for g in GRAPHS))

# -- the ratio --------------------------------------------------------------
c.close("approximation_ratio(4, 2)", lambda: approximation_ratio(4, 2), 2.0)
c.close("approximation_ratio(3, 3)", lambda: approximation_ratio(3, 3), 1.0)
c.close("a zero-cost answer to a zero optimum is ratio 1",
        lambda: approximation_ratio(0, 0), 1.0)
c.true("a nonzero answer to a zero optimum is infinitely bad",
       lambda: approximation_ratio(5, 0) == float("inf"))
c.close("the 5-edge graph gives ratio 2",
        lambda: approximation_ratio(len(vertex_cover_approx(SQUARE_PLUS)),
                                    _min_cover_size(SQUARE_PLUS)), 2.0)

# -- slide 20: the bound is tight ------------------------------------------
c.eq("tight_example(3) has 3 edges", lambda: len(tight_example(3)), 3)
c.eq("tight_example(3) has 6 distinct vertices",
     lambda: len({v for e in tight_example(3) for v in e}), 6)
c.true("its edges are disjoint — it is a matching",
       lambda: all(len({v for e in tight_example(k) for v in e}) == 2 * k
                   for k in (1, 2, 3, 5)))
c.true("np slide 20: the algorithm takes every vertex",
       lambda: all(len(vertex_cover_approx(tight_example(k))) == 2 * k
                   for k in (1, 2, 3, 5)))
c.true("...while half of them suffice",
       lambda: all(_min_cover_size(tight_example(k)) == k for k in (1, 2, 3)))
c.close("...so the ratio is exactly 2",
        lambda: approximation_ratio(len(vertex_cover_approx(tight_example(4))),
                                    4), 2.0)

# -- the triangle inequality, np slide 21 ----------------------------------
c.true("a Euclidean graph is metric",
       lambda: all(satisfies_triangle_inequality(g) for g in METRICS))
c.true("a graph with one huge detour-beating edge is not",
       lambda: not satisfies_triangle_inequality(
           {"a": {"a": 0, "b": 1, "c": 99}, "b": {"a": 1, "b": 0, "c": 1},
            "c": {"a": 99, "b": 1, "c": 0}}))

# -- MST --------------------------------------------------------------------
c.eq("a 4-vertex graph has 3 tree edges", lambda: len(mst_edges(RECT)), 3)
c.eq("the empty graph has no tree edges", lambda: mst_edges({}), [])
c.eq("the rectangle's MST", lambda: mst_edges(RECT),
     [("a", "b"), ("a", "d"), ("c", "d")])
c.close("the rectangle's MST weighs 10", lambda: mst_weight(RECT), 10.0, tol=1e-6)
c.close("the line's MST weighs 5", lambda: mst_weight(LINE), 5.0, tol=1e-6)
c.true("n vertices give n-1 tree edges",
       lambda: all(len(mst_edges(g)) == len(g) - 1 for g in METRICS))
c.true("the tree is connected — every vertex appears",
       lambda: all({v for e in mst_edges(g) for v in e} == set(g)
                   for g in METRICS))
c.true("no spanning tree is cheaper (rectangle)",
       lambda: all(mst_weight(RECT) <= sum(RECT[u][v] for u, v in tree) + 1e-9
                   for tree in [[("a", "b"), ("b", "c"), ("c", "d")],
                                [("a", "b"), ("a", "c"), ("a", "d")],
                                [("a", "d"), ("d", "c"), ("c", "b")]]))

# -- the tour, np slides 23-26 ---------------------------------------------
c.true("the tour visits every vertex exactly once",
       lambda: all(sorted(tsp_tour(g)) == sorted(g) for g in METRICS))
c.eq("the tour starts at the first vertex", lambda: tsp_tour(RECT)[0], "a")
c.eq("the empty graph has an empty tour", lambda: tsp_tour({}), [])
c.close("tour_cost closes the cycle",
        lambda: tour_cost(RECT, ["a", "b", "c", "d"]), 14.0, tol=1e-6)
c.eq("a one-vertex tour costs nothing", lambda: tour_cost(RECT, ["a"]), 0)
c.close("the rectangle's approximate tour costs 16",
        lambda: tour_cost(RECT, tsp_tour(RECT)), 16.0, tol=1e-6)
c.close("the rectangle's optimal tour costs 14",
        lambda: optimal_tour_cost(RECT), 14.0, tol=1e-6)

# The guarantee, and the fact that in practice it does much better.
c.true("np slide 23: the tour costs at most 2 * OPT",
       lambda: all(tour_cost(g, tsp_tour(g)) <= 2 * optimal_tour_cost(g) + 1e-9
                   for g in METRICS))
c.true("...and at most 2 * MST, which is the actual argument",
       lambda: all(tour_cost(g, tsp_tour(g)) <= 2 * mst_weight(g) + 1e-9
                   for g in METRICS))
c.true("MST <= OPT, the lower bound the proof rests on",
       lambda: all(mst_weight(g) <= optimal_tour_cost(g) + 1e-9 for g in METRICS))
c.true("in practice the ratio is well under 2",
       lambda: approximation_ratio(tour_cost(RECT, tsp_tour(RECT)),
                                   optimal_tour_cost(RECT)) < 1.5)
c.true("the tour is never cheaper than the optimum",
       lambda: all(tour_cost(g, tsp_tour(g)) >= optimal_tour_cost(g) - 1e-9
                   for g in METRICS))

sys.exit(c.done())
