"""Alg week 10 tests. You do not edit this file."""

import sys

from check import Check
from exercises import (cover_weight, greedy_set_cover, harmonic, is_set_cover,
                       max_frequency, max_subset_size, optimal_set_cover,
                       primal_dual_set_cover, round_lp_solution)

c = Check("Alg week 10 — set cover: greedy, rounding, primal-dual")

# Slide 28's instance.
G1 = {1, 2, 3, 4}
S1 = {"S1": {1, 2}, "S2": {1, 3}, "S3": {2, 4}, "S4": {2, 3, 4}}
W1 = {"S1": 1, "S2": 1, "S3": 1, "S4": 1}

# A weighted instance where taking more, cheaper sets wins.
G2 = set(range(1, 7))
S2 = {"A": {1, 2, 3}, "B": {4, 5, 6}, "C": {1, 2, 3, 4}, "D": {5, 6}}
W2 = {"A": 3, "B": 3, "C": 3.9, "D": 2}

# The classic instance where greedy is not optimal.
G3 = {1, 2, 3, 4, 5, 6}
S3 = {"L": {1, 2, 3, 4}, "R1": {1, 2, 5}, "R2": {3, 4, 6}}
W3 = {"L": 1, "R1": 1, "R2": 1}

INSTANCES = [(G1, S1, W1), (G2, S2, W2), (G3, S3, W3)]

# -- plumbing ---------------------------------------------------------------
c.eq("cover_weight of nothing is 0", lambda: cover_weight(W1, []), 0)
c.eq("cover_weight adds them up", lambda: cover_weight(W1, ["S1", "S4"]), 2)
c.close("cover_weight with float weights",
        lambda: cover_weight(W2, ["C", "D"]), 5.9, tol=1e-9)
c.true("is_set_cover accepts a cover", lambda: is_set_cover(G1, S1, ["S1", "S4"]))
c.true("is_set_cover rejects a partial one", lambda: not is_set_cover(G1, S1, ["S1"]))
c.true("nothing covers the empty ground set", lambda: is_set_cover(set(), S1, []))

# -- the two instance parameters -------------------------------------------
c.eq("slide 28: f = 3 because element 2 is in three sets",
     lambda: max_frequency(G1, S1), 3)
c.eq("max_frequency on the weighted instance", lambda: max_frequency(G2, S2), 2)
c.eq("max_frequency of an empty ground set is 0",
     lambda: max_frequency(set(), S1), 0)
c.eq("g = 3 on slide 28's instance", lambda: max_subset_size(S1), 3)
c.eq("max_subset_size of nothing is 0", lambda: max_subset_size({}), 0)
c.true("g <= n always",
       lambda: all(max_subset_size(s) <= len(g) for g, s, _ in INSTANCES))

# -- harmonic numbers -------------------------------------------------------
c.close("H_0 = 0", lambda: harmonic(0), 0.0)
c.close("H_1 = 1", lambda: harmonic(1), 1.0)
c.close("H_2 = 1.5", lambda: harmonic(2), 1.5)
c.close("H_4 = 25/12", lambda: harmonic(4), 25 / 12)
c.close("H_10", lambda: harmonic(10), 2.9289682539682538, tol=1e-9)
c.true("H_n grows like ln n", lambda: 4.5 < harmonic(100) < 5.5)
c.true("H_n is increasing", lambda: all(harmonic(n) < harmonic(n + 1)
                                        for n in range(1, 20)))

# -- the exact answer -------------------------------------------------------
c.close("slide 28's instance has optimum 2",
        lambda: cover_weight(W1, optimal_set_cover(G1, S1, W1)), 2.0, tol=1e-9)
c.close("the weighted instance has optimum 5.9",
        lambda: cover_weight(W2, optimal_set_cover(G2, S2, W2)), 5.9, tol=1e-9)
c.close("the greedy-trap instance has optimum 2",
        lambda: cover_weight(W3, optimal_set_cover(G3, S3, W3)), 2.0, tol=1e-9)
c.true("the optimum is always a valid cover",
       lambda: all(is_set_cover(g, s, optimal_set_cover(g, s, w))
                   for g, s, w in INSTANCES))
# The trap: on the weighted instance the cheapest *count* is 2 sets (A+B, cost
# 6) but the cheapest *weight* is also 2 sets (C+D, 5.9). Minimise weight.
c.eq("it minimises weight, not the number of sets",
     lambda: sorted(optimal_set_cover(G2, S2, W2)), ["C", "D"])

# -- greedy, slide 41 -------------------------------------------------------
c.true("greedy returns a valid cover",
       lambda: all(is_set_cover(g, s, greedy_set_cover(g, s, w))
                   for g, s, w in INSTANCES))
c.eq("greedy finds the optimum on slide 28's instance",
     lambda: sorted(greedy_set_cover(G1, S1, W1)), ["S1", "S4"])
c.true("greedy is never better than optimal",
       lambda: all(cover_weight(w, greedy_set_cover(g, s, w))
                   >= cover_weight(w, optimal_set_cover(g, s, w)) - 1e-9
                   for g, s, w in INSTANCES))

# Theorem 1.11 and 1.12, checked on every instance.
c.true("Theorem 1.11: greedy <= H_n * OPT",
       lambda: all(cover_weight(w, greedy_set_cover(g, s, w))
                   <= harmonic(len(g)) * cover_weight(w, optimal_set_cover(g, s, w)) + 1e-9
                   for g, s, w in INSTANCES))
c.true("Theorem 1.12: greedy <= H_g * OPT, which is the tighter bound",
       lambda: all(cover_weight(w, greedy_set_cover(g, s, w))
                   <= harmonic(max_subset_size(s))
                      * cover_weight(w, optimal_set_cover(g, s, w)) + 1e-9
                   for g, s, w in INSTANCES))
c.true("H_g is at least as tight as H_n",
       lambda: all(harmonic(max_subset_size(s)) <= harmonic(len(g)) + 1e-12
                   for g, s, _ in INSTANCES))

# Greedy picks by rate, not by size or by price.
c.eq("greedy takes the best rate, not the biggest set",
     lambda: sorted(greedy_set_cover({1, 2, 3}, {"big": {1, 2, 3}, "cheap": {1}},
                                     {"big": 10, "cheap": 1})),
     ["big", "cheap"])

# -- LP rounding, slides 28-30 ---------------------------------------------
c.eq("round_lp_solution takes everything at x = 1/f",
     lambda: sorted(round_lp_solution(S1, {"S1": 0.5, "S2": 0.5, "S3": 0.5,
                                           "S4": 0.5}, 3)),
     ["S1", "S2", "S3", "S4"])
c.eq("...and nothing below the threshold",
     lambda: sorted(round_lp_solution(S1, {"S1": 0.2, "S2": 0.2, "S3": 0.2,
                                           "S4": 0.2}, 3)), [])
c.eq("exactly 1/f is included (the inequality is >=)",
     lambda: sorted(round_lp_solution(S1, {"S1": 1 / 3, "S2": 0.0, "S3": 0.0,
                                           "S4": 0.0}, 3)), ["S1"])
c.eq("f = 0 gives the empty selection",
     lambda: round_lp_solution(S1, {"S1": 1.0}, 0), set())
c.eq("an integral LP solution rounds to itself",
     lambda: sorted(round_lp_solution(S1, {"S1": 1.0, "S2": 0.0, "S3": 0.0,
                                           "S4": 1.0}, 3)), ["S1", "S4"])

# Lemma 1.5: rounding a *feasible* LP solution always yields a cover.
c.true("Lemma 1.5: rounding the all-1/f solution covers everything",
       lambda: all(is_set_cover(g, s,
                                round_lp_solution(s, {j: 1.0 / max_frequency(g, s)
                                                      for j in s},
                                                  max_frequency(g, s)))
                   for g, s, _ in INSTANCES))

# -- primal-dual, slides 34-39 ---------------------------------------------
c.true("primal-dual returns a valid cover",
       lambda: all(is_set_cover(g, s, primal_dual_set_cover(g, s, w))
                   for g, s, w in INSTANCES))
c.eq("primal-dual on an empty ground set chooses nothing",
     lambda: primal_dual_set_cover(set(), S1, W1), set())
c.true("Theorem 1.9: primal-dual <= f * OPT",
       lambda: all(cover_weight(w, primal_dual_set_cover(g, s, w))
                   <= max_frequency(g, s)
                      * cover_weight(w, optimal_set_cover(g, s, w)) + 1e-9
                   for g, s, w in INSTANCES))
c.true("primal-dual is never better than optimal",
       lambda: all(cover_weight(w, primal_dual_set_cover(g, s, w))
                   >= cover_weight(w, optimal_set_cover(g, s, w)) - 1e-9
                   for g, s, w in INSTANCES))
c.true("a single set covering everything is taken alone",
       lambda: primal_dual_set_cover({1, 2}, {"all": {1, 2}}, {"all": 5}) == {"all"})

# All three are approximations of the same thing, and all three are feasible.
c.true("all three produce covers of the same instance",
       lambda: all(is_set_cover(G2, S2, alg(G2, S2, W2))
                   for alg in (greedy_set_cover, primal_dual_set_cover,
                               optimal_set_cover)))

sys.exit(c.done())
