"""Where are we in the semester, what is due, and is anything missing?

    python src/week.py            # pull from GitHub, then the current week
    python src/week.py --all      # whole semester at a glance
    python src/week.py --no-pull  # skip the GitHub check (offline, say)

It starts by bringing this clone up to date with GitHub, because the repo is
used from more than one machine and forgetting to pull once is how the two
clones drifted apart for a month (see task.md, T-009). It only pulls when that
is a clean fast-forward: on main, nothing uncommitted, nothing unpushed. In
every other case it says what it found and leaves your files alone.

Future weeks are never reported as missing — if a folder is empty it is almost
certainly because the lecturer has not published anything yet.

Each week's README.md is generated by canvas_sync.py, so "record" in the status
line means Canvas has been synced for that week, not that anyone wrote anything.
"""

import argparse
import json
import subprocess
from datetime import date, datetime, timezone

from paths import ROOT

try:                                    # stdlib since 3.9; only used for display
    from zoneinfo import ZoneInfo
    OSLO = ZoneInfo("Europe/Oslo")
except Exception:                       # pragma: no cover - fall back to UTC
    OSLO = timezone.utc

# uke -> (part, topic). Mirrors the Canvas semester plan; update when it changes.
PLAN = {
    34: ("ml", "ML modul 1: Introduksjon til maskinlæring"),
    35: ("alg", "Algoritmer - Tekstprosessering"),
    36: ("ml", "ML modul 1: Introduksjon til maskinlæring"),
    37: ("alg", "Algoritmer - NP-completeness, Chapter 1"),
    38: ("alg", "Chapter 2"),
    39: ("ml", "ML modul 2: Maskinlæringsmodeller"),
    40: ("ml", "ML modul 2: Maskinlæringsmodeller"),
    41: ("alg", "Ons: ML modul 3 (forelesning 9) / Fre: Algoritmer - Chapter 3"),
    42: ("alg", "(ikkje kunngjort enno)"),
    43: ("ml", "Ons: Algoritmer / Fre: ML modul 3: End-to-end maskinlæringssystem"),
    44: ("ml", "ML modul 3: End-to-end maskinlæringssystem"),
    45: ("alg", "Chapter 6 & 7"),
    46: ("alg", "(ikkje kunngjort enno)"),
    47: ("ml", "(ikkje kunngjort enno)"),
}


DATES = {
    34: "17. - 23. aug", 35: "24. - 30. aug", 36: "31. aug - 6. sep",
    37: "7. - 13. sep", 38: "14. - 20. sep", 39: "21. - 27. sep",
    40: "28. sep - 4. okt", 41: "5. - 11. okt", 42: "12. - 18. okt",
    43: "19. - 25. okt", 44: "26. okt - 1. nov", 45: "2. - 8. nov",
    46: "9. - 15. nov", 47: "16. - 21. nov",
}


def folder(uke: int):
    part, _ = PLAN[uke]
    return ROOT / "weeks" / f"uke{uke}-{part}"


def survey(uke: int) -> dict:
    """What exists in a week's folder. Counts, not judgements."""
    d = folder(uke)

    def count(sub):
        p = d / sub
        return len([f for f in p.iterdir() if f.name != ".gitkeep"]) if p.exists() else 0

    return {
        "record": (d / "README.md").exists(),
        "slides": count("slides"),
        "code": count("code"),
        "exercises": count("exercises"),
    }


def deadlines() -> list[tuple[date, str]]:
    """Assignment due dates, from the Canvas snapshot. Empty if it has not synced.

    Canvas stores due_at in UTC; a 23:59 Norwegian deadline is 21:59Z in summer,
    so convert before taking the date or everything lands a day early.
    """
    snap = ROOT / "docs" / "canvas" / "raw" / "snapshot.json"
    if not snap.exists():
        return []
    try:
        data = json.loads(snap.read_text())
    except (json.JSONDecodeError, OSError):
        return []

    out = []
    for a in data.get("assignments", []):
        due, name = a.get("due_at"), a.get("name")
        if not due or not name:
            continue
        try:
            when = datetime.fromisoformat(due.replace("Z", "+00:00"))
        except ValueError:
            continue
        out.append((when.astimezone(OSLO).date(), name))
    return sorted(out)


def report_deadlines(today: date) -> None:
    """Print what is due, loudest first. Silent when there is nothing."""
    upcoming = [(d, n) for d, n in deadlines() if d >= today]
    if not upcoming:
        return

    print("Due:")
    for d, name in upcoming[:5]:
        days = (d - today).days
        if days == 0:
            urgency = "TODAY"
        elif days == 1:
            urgency = "TOMORROW"
        else:
            urgency = f"{days} days"
        flag = "  <-- " if days <= 3 else "      "
        print(f"  {d:%d %b}  {urgency:<9}{flag}{name}")
    print()


def line(uke: int, current: int) -> str:
    part, topic = PLAN[uke]
    s = survey(uke)
    marker = ">" if uke == current else " "
    when = "future" if uke > current else ("NOW" if uke == current else "past")

    bits = []
    bits.append("record" if s["record"] else "-")
    bits.append(f"{s['slides']} slides" if s["slides"] else "-")
    bits.append(f"{s['code']} code" if s["code"] else "-")
    bits.append(f"{s['exercises']} exc" if s["exercises"] else "-")

    return f"{marker} uke{uke} {part:<3} {when:<6} [{' | '.join(bits)}]  {topic[:44]}"


def _git(*args: str, timeout: int = 20) -> subprocess.CompletedProcess:
    return subprocess.run(["git", "-C", str(ROOT), *args],
                          capture_output=True, text=True, timeout=timeout)


def sync_with_github() -> None:
    """Pull from GitHub when that is a safe fast-forward; otherwise explain."""
    try:
        if _git("fetch", "--quiet", "origin").returncode != 0:
            print("GitHub: could not reach it (offline?) — not pulled.\n")
            return
    except (OSError, subprocess.TimeoutExpired):
        print("GitHub: no answer within 20 s — not pulled.\n")
        return

    branch = _git("branch", "--show-current").stdout.strip()
    counts = _git("rev-list", "--left-right", "--count", "HEAD...origin/main").stdout.split()
    ahead, behind = (int(counts[0]), int(counts[1])) if len(counts) == 2 else (0, 0)
    dirty = bool(_git("status", "--porcelain", "--untracked-files=no").stdout.strip())

    if branch != "main":
        print(f"GitHub: you are on '{branch}', not main — not pulled.\n")
    elif ahead and behind:
        print(f"GitHub: DIVERGED — {ahead} commit(s) only here, {behind} only on GitHub.\n"
              "        Not pulled. Sort this out before committing more (ask Claude).\n")
    elif behind and dirty:
        print(f"GitHub: {behind} new commit(s), but you have uncommitted changes — not pulled.\n"
              "        Commit them (or `git stash`), then run this again.\n")
    elif behind:
        r = _git("pull", "--ff-only", "--quiet", "origin", "main", timeout=120)
        if r.returncode == 0:
            print(f"GitHub: pulled {behind} new commit(s) from your other machine.\n")
        else:
            print(f"GitHub: pull failed — {r.stderr.strip() or 'unknown error'}\n")
    elif ahead:
        print(f"GitHub: {ahead} commit(s) here are not on GitHub yet — `git push` when done.\n")
    else:
        print("GitHub: up to date.\n")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--all", action="store_true", help="show every week")
    ap.add_argument("--no-pull", action="store_true", help="skip the GitHub check")
    args = ap.parse_args()

    if not args.no_pull:
        sync_with_github()

    today = date.today()
    current = today.isocalendar().week

    print(f"Today: {today:%Y-%m-%d} — ISO week {current}")

    if current < min(PLAN):
        print(f"Semester starts in uke {min(PLAN)}.")
        return 0
    if current > max(PLAN):
        print(f"Teaching ended in uke {max(PLAN)}. Exam period — see exam/.")
        return 0

    part, topic = PLAN[current]
    print(f"Current: uke{current} ({part.upper()}) — {topic}")
    print(f"Folder:  weeks/uke{current}-{part}/\n")

    report_deadlines(today)

    weeks = sorted(PLAN) if args.all else [u for u in sorted(PLAN) if u <= current]
    for uke in weeks:
        print(line(uke, current))

    # Only ever chase weeks that have already happened.
    gaps = [u for u in sorted(PLAN) if u <= current and not survey(u)["slides"]]
    if gaps:
        print(
            "\nNo slides filed for: "
            + ", ".join(f"uke{u}" for u in gaps)
            + "\nIf the lecturer hasn't published them yet, that's expected — ignore."
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
